name: Validate PyScript filesystem TOML

on:
  push:
    branches: [main]
    paths:
      - "lib/**"
      - "utils/**"
      - "board_configs/desktop/**"
      - "pydevices-desktop.toml"
  pull_request:
    paths:
      - "lib/**"
      - "utils/**"
      - "board_configs/desktop/**"
      - "pydevices-desktop.toml"
  workflow_dispatch:

jobs:
  validate:
    uses: PyDevices/.github/.github/workflows/reusable-validate-pyscript-filesystem-toml.yml@publishing-v6
    with:
      config-path: pydevices-desktop.toml
      source-mappings: |
        lib=/lib
        utils=/lib
      file-mappings: |
        board_configs/desktop/board_config.py=/lib/board_config.py
        board_configs/desktop/board_peripherals.py=/lib/board_peripherals.py
